/** Places offered in the "Where to" suggestions and recognised when typed inside a sentence.
 * Any place can still be typed by hand: live rates come from the hotel provider for whatever is entered. */
export const popularDestinations: { name: string; country: string }[] = [
  { name: "Paris", country: "France" },
  { name: "Tokyo", country: "Japan" },
  { name: "New York", country: "United States" },
  { name: "Lagos", country: "Nigeria" },
  { name: "Bali", country: "Indonesia" },
  { name: "London", country: "United Kingdom" },
  { name: "Lisbon", country: "Portugal" },
  { name: "Porto", country: "Portugal" },
  { name: "Madrid", country: "Spain" },
  { name: "Barcelona", country: "Spain" },
  { name: "Seville", country: "Spain" },
  { name: "Rome", country: "Italy" },
  { name: "Milan", country: "Italy" },
  { name: "Florence", country: "Italy" },
  { name: "Venice", country: "Italy" },
  { name: "Amsterdam", country: "Netherlands" },
  { name: "Berlin", country: "Germany" },
  { name: "Munich", country: "Germany" },
  { name: "Vienna", country: "Austria" },
  { name: "Prague", country: "Czechia" },
  { name: "Budapest", country: "Hungary" },
  { name: "Athens", country: "Greece" },
  { name: "Santorini", country: "Greece" },
  { name: "Istanbul", country: "Turkey" },
  { name: "Dublin", country: "Ireland" },
  { name: "Edinburgh", country: "United Kingdom" },
  { name: "Zurich", country: "Switzerland" },
  { name: "Copenhagen", country: "Denmark" },
  { name: "Stockholm", country: "Sweden" },
  { name: "Oslo", country: "Norway" },
  { name: "Reykjavik", country: "Iceland" },
  { name: "Warsaw", country: "Poland" },
  { name: "Dubrovnik", country: "Croatia" },
  { name: "Dubai", country: "United Arab Emirates" },
  { name: "Abu Dhabi", country: "United Arab Emirates" },
  { name: "Doha", country: "Qatar" },
  { name: "Riyadh", country: "Saudi Arabia" },
  { name: "Tel Aviv", country: "Israel" },
  { name: "Cairo", country: "Egypt" },
  { name: "Marrakech", country: "Morocco" },
  { name: "Cape Town", country: "South Africa" },
  { name: "Johannesburg", country: "South Africa" },
  { name: "Nairobi", country: "Kenya" },
  { name: "Accra", country: "Ghana" },
  { name: "Abuja", country: "Nigeria" },
  { name: "Kigali", country: "Rwanda" },
  { name: "Zanzibar", country: "Tanzania" },
  { name: "Addis Ababa", country: "Ethiopia" },
  { name: "Dakar", country: "Senegal" },
  { name: "Bangkok", country: "Thailand" },
  { name: "Phuket", country: "Thailand" },
  { name: "Singapore", country: "Singapore" },
  { name: "Kuala Lumpur", country: "Malaysia" },
  { name: "Hong Kong", country: "Hong Kong" },
  { name: "Seoul", country: "South Korea" },
  { name: "Osaka", country: "Japan" },
  { name: "Kyoto", country: "Japan" },
  { name: "Shanghai", country: "China" },
  { name: "Beijing", country: "China" },
  { name: "Taipei", country: "Taiwan" },
  { name: "Hanoi", country: "Vietnam" },
  { name: "Ho Chi Minh City", country: "Vietnam" },
  { name: "Manila", country: "Philippines" },
  { name: "Jakarta", country: "Indonesia" },
  { name: "Mumbai", country: "India" },
  { name: "Delhi", country: "India" },
  { name: "Goa", country: "India" },
  { name: "Colombo", country: "Sri Lanka" },
  { name: "Kathmandu", country: "Nepal" },
  { name: "Los Angeles", country: "United States" },
  { name: "San Francisco", country: "United States" },
  { name: "Chicago", country: "United States" },
  { name: "Miami", country: "United States" },
  { name: "Las Vegas", country: "United States" },
  { name: "Washington DC", country: "United States" },
  { name: "Boston", country: "United States" },
  { name: "Seattle", country: "United States" },
  { name: "Toronto", country: "Canada" },
  { name: "Vancouver", country: "Canada" },
  { name: "Montreal", country: "Canada" },
  { name: "Mexico City", country: "Mexico" },
  { name: "Cancun", country: "Mexico" },
  { name: "Havana", country: "Cuba" },
  { name: "Bogota", country: "Colombia" },
  { name: "Medellin", country: "Colombia" },
  { name: "Lima", country: "Peru" },
  { name: "Rio de Janeiro", country: "Brazil" },
  { name: "Sao Paulo", country: "Brazil" },
  { name: "Buenos Aires", country: "Argentina" },
  { name: "Santiago", country: "Chile" },
  { name: "Sydney", country: "Australia" },
  { name: "Melbourne", country: "Australia" },
  { name: "Auckland", country: "New Zealand" },
  { name: "Queenstown", country: "New Zealand" },
];
